version: '3.2'
services:
  web:
    build: 
      context: ./core
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ..:/app/
      - '~/.vscode-server:/root/.vscode-server'
    sysctls:
      - net.core.somaxconn=32768